name: "Terraform Plan"

on:
  pull_request:
    branches:
      - main
    
env:
  TF_CLOUD_ORGANIZATION: "digodk-tutorial"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "bot-bot"
  CONFIG_DIRECTORY: "./"

jobs:
  